Rename ./pdb to ./uberjar
the script at ./ovdb used to be a different tool also called pdb. Rename
./pdb to avoid confusion with that old tool.

diff --git a/uberjar b/uberjar
--- a/uberjar
+++ b/uberjar
@@ -5,8 +5,8 @@
 # The Bouncycastle dependency jars can be specified with BCPROV_JAR and BCPKIX_JAR
 # Must have PostgreSQL running for PuppetDB to work
 # Any arguments get passed straight to PuppetDB
-# Example: pdb --help
-# Example: pdb services --config ~/tmp/pdb-sandbox/conf.d
+# Example: uberjar --help
+# Example: uberjar services --config ~/tmp/pdb-sandbox/conf.d
 
 set -eo pipefail
 
@@ -26,15 +26,15 @@ cache_checked=''
 # Save Bouncy Castle package versions to local filesystem
 ensure-cache()
 {
-    if test ! -e ./pdb.bcprov -o ./project.clj -nt ./pdb.bcprov \
-            -o ! -e ./pdb.bcpkix -o ./project.clj -nt ./pdb.bcpkix; then
+    if test ! -e ./uberjar.bcprov -o ./project.clj -nt ./uberjar.bcprov \
+            -o ! -e ./uberjar.bcpkix -o ./project.clj -nt ./uberjar.bcpkix; then
         if test "$cache_checked"; then
-            echo 'error: pdb.* or project.clj changed during execution' 1>&2
+            echo 'error: uberjar.* or project.clj changed during execution' 1>&2
             exit 2
         fi
         local deps=$(lein deps :tree)
-        dep-ver org.bouncycastle/bcpkix-jdk18on "$deps" > ./pdb.bcpkix
-        dep-ver org.bouncycastle/bcprov-jdk18on "$deps" > ./pdb.bcprov
+        dep-ver org.bouncycastle/bcpkix-jdk18on "$deps" > ./uberjar.bcpkix
+        dep-ver org.bouncycastle/bcprov-jdk18on "$deps" > ./uberjar.bcprov
     fi
     cache_checked=true
 }
@@ -59,7 +59,7 @@ if test "$BCPROV_JAR"; then
     bcprov="$BCPROV_JAR"
 else
     ensure-cache
-    bcprov_ver=$(<./pdb.bcprov)
+    bcprov_ver=$(<./uberjar.bcprov)
     bcprov="$HOME/.m2/repository/org/bouncycastle/bcprov-jdk18on/$bcprov_ver/bcprov-jdk18on-$bcprov_ver.jar"
 fi
 
@@ -69,7 +69,7 @@ if test "$BCPKIX_JAR"; then
     bcpkix="$BCPKIX_JAR"
 else
     ensure-cache
-    bcpkix_ver=$(<./pdb.bcpkix)
+    bcpkix_ver=$(<./uberjar.bcpkix)
     bcpkix="$HOME/.m2/repository/org/bouncycastle/bcpkix-jdk18on/$bcpkix_ver/bcpkix-jdk18on-$bcpkix_ver.jar"
 fi
 
